version: "3"
tasks:
  sql:
    desc: Run SQL tests
    dir: sql
    cmds:
      - docker compose up --detach --wait
      - defer: docker compose down
      - go test -count=1 -timeout=30m ./...

  bench:
    desc: Run CPU and memory benchmarks
    dir: bench
    cmds:
      - go test -count=20 -timeout=120m -bench . > benchcpu.txt
      - benchstat -filter ".unit:ns/op" -col /mod benchcpu.txt
      - go test -count=1 -timeout=30m -benchmem -bench . > benchmem.txt
      - benchstat -filter ".unit:B/op" -col /mod benchmem.txt
