on:
  push:
    branches: [main]
name: money
jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: stable 
        cache: false

    - name: Setup Task
      uses: arduino/setup-task@v2

    - name: Check out code
      uses: actions/checkout@v4

    - name: Verify code formatting
      run: gofmt -s -w . && git diff --exit-code

    - name: Verify dependency consistency
      run: go get -u -t ./... && go mod tidy && git diff --exit-code

    - name: Verify potential issues
      uses: golangci/golangci-lint-action@v4

    - name: Run fuzz tests
      run: task fuzz
      